const IconsForType = {
  'ban': 'ban',
  'error': 'exclamation-circle',
  'warning': 'exclamation-triangle',
  'success': 'check-circle',
  'folder': 'folder-o',
  'openFolder': 'folder-open-o',
  'table': 'table',
  'close': 'remove',
  'cached': 'check', // TODO(someone): find a better icon for cached table
  'inProgress': 'spinner fa-spin',
  'shell': 'file-text-o',
  'dashboard': 'bar-chart',
  'library': 'book',
  'setting': 'gear',
  'help': 'question',
  'cluster': 'sitemap',
  'view': 'picture-o',
  'comments': 'comments',
  'github': 'github',
  'lock': 'lock',
  'example': 'question',
  'user': 'user',
  'users': 'users',
  'shared': 'share-alt-square',
  'jobs': 'calendar',
  'recent': 'clock-o',
  'apps': 'th',
  'workspace': 'folder-open-o',
  'search': 'search',
  // home folder for the current user
  'home': 'home',
  // home folders for other users
  'userFolder': 'folder',
  'openUserFolder': 'folder-open',
  'history': 'history',
  'runAll': 'play-circle-o',
  'stopRunAll': 'stop',
  'clearResults': 'eraser',
  'chevronUp': 'chevron-up',
  'chevronDown': 'chevron-down',
  'chevronRight': 'chevron-right',
  'document': 'file-o',
  'create': 'plus',
  'link': 'external-link',
  'navigate': 'external-link',
  'left': 'align-left',
  'right': 'align-right',
  'center': 'align-center',
  'refresh': 'refresh',
  'zoomLarge': 'search-plus',
  'zoomSmall': 'search-minus',
  'active': 'check',
  'publish': 'share-square-o',
  // a hint icon usually accompanied by a tooltip or link for more information: (?)
  'hint': 'question-circle help-icon',
  // icon for importing notebook from a static notebook
  // icon for export to html of job run results
  'download': 'cloud-download',
  'import': 'cloud-upload',
};

module.exports = IconsForType;
